# -*- coding: utf-8 -*-
"""populaton_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rboiL4CNS_UnTeypl_J1SBweUPAOEr5_
"""

import matplotlib.pyplot as plt
years = [1950,1970,1990,2010]
population = [2.519,3.692,5.265,6.994]
plt.plot(years, population)
plt.show()

plt.scatter(years, population)
plt.show()